name: java-ci-cd-pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  APP_NAME: product-service
  IMAGE_NAME: product-service
  DOCKER_REGISTRY: docker.io
  K8S_MANIFEST_PATH: k8s/deployment.yaml

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}

      - name: Build & Unit Tests
        run: mvn clean verify

  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Sonar Scan
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=${{ env.APP_NAME }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  dependency-check:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - uses: actions/checkout@v4

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "${{ env.APP_NAME }}"
          path: "."
          format: "HTML"
          out: "dependency-check-report"

  trivy-fs:
    name: Trivy Filesystem Scan
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - uses: actions/checkout@v4

      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: 1

  docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs:
      - sonar
      - dependency-check
      - trivy-fs

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}

  trivy-image:
    name: Trivy Image Scan
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
          severity: HIGH,CRITICAL
          exit-code: 1

  dast:
    name: DAST - OWASP ZAP
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: "http://staging.mycompany.com"
          rules_file_name: zap-rules.conf
        env:
          ZAP_TOKEN: ${{ secrets.ZAP_API_TOKEN }}

  update-k8s:
    name: Update Kubernetes Manifests
    runs-on: ubuntu-latest
    needs:
      - trivy-image
      - dast

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Image Tag
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}|" ${{ env.K8S_MANIFEST_PATH }}

      - name: Commit & Push Changes
        run: |
          git config user.email "ci@company.com"
          git config user.name "GitHub Actions"
          git add ${{ env.K8S_MANIFEST_PATH }}
          git commit -m "[CI] Update image tag"
          git push origin main
